/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    ApprovePurgatoryBookButton: typeof import('./src/components/ApprovePurgatoryBookButton.vue')['default']
    BookEditForm: typeof import('./src/components/BookEditForm.vue')['default']
    BooksActionsCell: typeof import('./src/components/BooksActionsCell.vue')['default']
    BookUpsertSlideover: typeof import('./src/components/BookUpsertSlideover.vue')['default']
    BulkDeleteBooksButton: typeof import('./src/components/BulkDeleteBooksButton.vue')['default']
    CrawlJobCancelButton: typeof import('./src/components/CrawlJobCancelButton.vue')['default']
    CrawlJobErrorsButton: typeof import('./src/components/CrawlJobErrorsButton.vue')['default']
    CrawlJobErrorsTable: typeof import('./src/components/CrawlJobErrorsTable.vue')['default']
    CrawlJobStatus: typeof import('./src/components/CrawlJobStatus.vue')['default']
    DeleteBookButton: typeof import('./src/components/DeleteBookButton.vue')['default']
    DeletePurgatoryBookButton: typeof import('./src/components/DeletePurgatoryBookButton.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortableColumnHeader: typeof import('./src/components/SortableColumnHeader.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UFieldGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputTags: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue')['default']
    UKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageHero: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
    UPagination: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_fffde12c052a88aae3f39332513dd1e6/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
  }
}
